### PR TITLE
Qr code pages

### LINKED ISSUE #12: Token collector feature views
- users can collect tokens using QR codes
- recommended lib: [https://github.com/nimiq/qr-scanner](https://github.com/nimiq/qr-scanner)
- submit token 
  - endpoint: POST /api/token/:tokenId
  - response: {"status": enum {SCANNED, ALREADY_SCANNED, WRONG}, "title": String?}
- QR codes are urls
  - GET {baseUrl}/api/qr/{token}
  - session check (authsch) -> redeem -> redirect:done [GET /qr-scanned?query]
  - query: {"status": enum {SCANNED, ALREADY_SCANNED, WRONG}, "title": String?}

### LINKED ISSUE #33: QR pages
QR list page
- List scanned QRs
- QR scan button

QR scan page
- QR lib to use camera etc.
- Checkmark or X when scan is completed

### PR DESCRIPTION
**Pull request by poiuztrewq1**
Done the views for token collection:
 - Show progress, and list already scanned codes
 - Scan new qr code
 - Redirect page for manual 
 
Wired in axios requests in the list view and scan view, but i think we should outsource the api communication in  a service file and handle network errors in one place, that way the pages would look nicer, and the error handling would be the same across the site.

I didn't use the [recommended](https://github.com/nimiq/qr-scanner) QR lib, because i would have to manually wire in a service worker js file, but the `react-qr-reader` package does it for me. 
The QR reader right now won't work because there is a bug on backend side with the post API.

!! 
> Due to browser implementations the camera can only be accessed over https or localhost.

closes #33 
closes #12

### CODE REVIEW

File: src/main/client/src/components/@pages/QRList.tsx [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+      </Button>
+
+      <Heading>Haladás</Heading>
+      <Heading as="h4" size="md">
+        Eddig beolvasott tokenek: {token_response.length} / 5
+      </Heading>
+
+      <Progress hasStripe colorScheme="brand" value={(100 * token_response.length) / 5} />
+      <Heading as="h4" size="md">
+        Amhol eddig jártál
```
Comment (berenteb) [inline src/main/client/src/components/@pages/QRList.tsx:42]: Whoops typo

File: src/main/client/src/components/@pages/QRList.tsx [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+
+  return (
+    <Page {...props}>
+      <Heading>QR kód vadászat</Heading>
+      <Paragraph>
+        A standoknál végzett aktív tevékenyégért QR kódokat lehet gyűjteni, amiket tanköri hiányzások igazolására lehet beváltani. TODO:
+        Fogalmazzunk meg ide szöveget, mert ma bevettem a fogalmazás gátlóm.
+      </Paragraph>
+
+      <Button colorScheme={'brand'} leftIcon={<FaQrcode />} onClick={scanEventHandler}>
```
Comment (berenteb) [inline src/main/client/src/components/@pages/QRList.tsx:31]: Very big button. Little too big. Wrap it inside a ButtonGroup!

File: src/main/client/src/components/@pages/QRList.tsx [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+      </Heading>
+
+      <Progress hasStripe colorScheme="brand" value={(100 * token_response.length) / 5} />
+      <Heading as="h4" size="md">
+        Amhol eddig jártál
+      </Heading>
+      <Stack spacing="5" alignItems={'center'}>
+        {token_response.map((token, i) => {
+          return (
+            <Box key={i} maxW={'md'} minW={'md'} borderWidth="1px" borderRadius={'lg'} boxShadow="lg" bg="brand.100">
```
Comment (berenteb) [inline src/main/client/src/components/@pages/QRList.tsx:47]: It's coming together. I know it's a WIP. On mobile it is not responsive, ande the corner of the image overflows the rounded parent component. Also, remove the border IMO, just use shadows if the background color is not transparent.

**Review by berenteb — CHANGES_REQUESTED** [review]

**Comment by berenteb** [comment]
The redirect page is awesome! Keep it up!

File: src/main/client/src/App.tsx [hunk 4]
```diff
@@ -45,6 +48,11 @@ export function App() {
                 <Route index element={<AchievementList />} />
               </Route>
               {/*QR*/}
+              <Route path="qr-scanned" element={<QRScanResult />}></Route>
```
Comment (berenteb) [inline src/main/client/src/App.tsx:51]: Move this inside the QR route as /qr/szkennelt. Alos use ungarische route names IMO.

File: src/main/client/src/components/@commons/QRScanResultComponent.tsx [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+      default:
+        return 'Hibás státusz kód'
+    }
+  }
+
+  return (
+    <Box>
+      {response.title && (
+        <Center>
+          <Heading>{response.title}</Heading>
```
Comment (berenteb) [inline src/main/client/src/components/@commons/QRScanResultComponent.tsx:41]: I think this is the heading that should be reduced in size, since its current size matches the page title.

File: src/main/client/src/components/@commons/QRScanResultComponent.tsx [hunk 6]
```diff
@@ -0,0 +1,52 @@
...
+        </Center>
+      )}
+      <Center p="40px" mt="4">
+        {renderIcon()}
+      </Center>
+      <Center>
+        <Heading>{getInfoText()}</Heading>
```
Comment (berenteb) [inline src/main/client/src/components/@commons/QRScanResultComponent.tsx:48]: Or this.

File: src/main/client/src/components/@commons/StampComponent.tsx [hunk 7]
```diff
@@ -0,0 +1,28 @@
+import { Box, Center, Flex, Icon, Stat, StatHelpText, StatLabel } from '@chakra-ui/react'
+import React from 'react'
+import { FaStamp } from 'react-icons/fa'
+
+interface StampComponentProps {
+  title?: string
+  type: string
+}
+
+export const StampComponent: React.FC<StampComponentProps> = ({ title, type }: StampComponentProps) => {
```
Comment (berenteb) [inline src/main/client/src/components/@commons/StampComponent.tsx:10]: I would make it gray as the CardListItem at the community list. But just a suggestion, will talk about it later.

File: src/main/client/src/components/@pages/QRScanResult.tsx [hunk 8]
```diff
@@ -0,0 +1,37 @@
...
+    navigate('/qr/scan')
+  }
+  const backButtonHandler = () => {
+    navigate('/qr')
+  }
+
+  return (
+    <Page {...props}>
+      <QRScanResultComponent response={server_response} />
+      <ButtonGroup spacing="6">
```
Comment (berenteb) [inline src/main/client/src/components/@pages/QRScanResult.tsx:27]: Képernyőfotó 2022-01-18 - 9 11 01
Center it please!

Comment (berenteb) [reply src/main/client/src/components/@pages/QRScanResult.tsx:27]: This what I was talking about when I said the heading size matches the page title. The icons and the layout will be dope though!

**Review by berenteb — CHANGES_REQUESTED** [review]
It is coming together, nice work!
A few things I noticed:
- I can't get the QR scanning to work. I think the backend fails for some reason.
- I see you have a profiles DTO and an enum for roles. Please contact the developer of the profile page whether he has similar types.
- Keep an exe on the paddings in the future, there will be issues created for adjusting paddings in every area of the project.
- We'll come back to the stamp list item color later

File: src/main/client/src/App.tsx (hunk 4 above)
Comment (poiuztrewq1) [reply src/main/client/src/App.tsx:51]: This path comes from the backend, because it redirects to this page with the appropriate results as query when someone manually redeems the code. Contact Schámi if you another route.

**Comment by triszt4n** [comment]
For some reason the QR reader does not work for me on mobile in Firefox browser.

**Comment by poiuztrewq1** [comment]
> On iOS some features are only available via HTTPS. Might be the case on Android Firefox.

It seems it's not a configuration problem, but a security concern in devices with camera.
Some quotes from the lib used. 

> Due to browser implementations the camera can only be accessed over https or localhost.`

And some unique programming on behalf of the bitten fruit company

> On IOS 11 it is only supported on Safari and not on Chrome or Firefox due to Apple making the API not available to 3rd party browsers.

**Comment by berenteb** [comment]
>  On IOS 11 it is only supported on Safari and not on Chrome or Firefox due to Apple making the API not available to 3rd party browsers.

Haha, yes, typical.

**Review by triszt4n — APPROVED** [review]
🧄 
🐶

**Comment by berenteb** [comment]
Is it working btw? I was having issues with the token.

**Review by berenteb — COMMENTED** [review]
amspeed

**Review by berenteb — APPROVED** [review]
